### ISSUE TITLE
The new version may have some kind of bug in GitHub Action.

### ISSUE THREAD

**Issue by gledos** [sondregronas/mkdocs-callouts#14]
Hi, In my MkDocs repository <https://github.com/gledos/ggame>, there is a clear difference between the local and GitHub Action builds.

This problem appears after the new version. Even though I have used the breakless_lists configuration, the GitHub Pages version built by GitHub Action still "breaks".

Below is a screenshot of local and [GitHub Action (Pages)](https://ggame.gledos.science/game/碧海黑帆.html):

![圖片](https://github.com/sondregronas/mkdocs-callouts/assets/23720620/7a18149d-1d1b-4f9b-a89d-245eafbf2adb)

![圖片](https://github.com/sondregronas/mkdocs-callouts/assets/23720620/5a353e83-42b5-4853-9898-2bce758b4914)

```markdown
## 简介

> [!summary inline end]+ 元数据
>
> ![标志](https://s3.tebi.io/ggame/ShareX/game_碧海黑帆_416531.webp "https://www.steamgriddb.com/grid/416531")
>
> ```yaml
> 标题:
> - 英文: "Skull and Bones"
> - 简体中文: "碧海黑帆"
> - 繁体中文: "怒海戰記"
> - 非官方直译: ["骷髅与骸骨", "骨与骸"]
> ```

《碧海黑帆》是育碧新加坡开发的战略动作游戏，基于《刺客信条：黑帆》的海上玩法。在多年的延期后，
```

Here are shortcut links to some warehouses:

+   [configuration file](https://github.com/gledos/ggame/blob/master/mkdocs.yml)
+   [Screenshot of the original Markdown text of the article](https://github.com/gledos/ggame/blob/master/docs/game/碧海黑帆.md)

This problem seems to only occur once on a page, and subsequent callouts will not be "breaks" again. But I don't know the specific cause of the failure.

Finally thank you very much for your software.

**Comment by gledos** [comment]
I don't know exactly which version caused the error. Probably only for a few months.

**Comment by sondregronas** [comment]
Thank you for reporting this, the issue was from the latest hotfix, and not within GitHub Actions - I was able to reproduce it locally.

The new version (1.13.2) should have this resolved, as it treats codefences inside callouts as if they were part of the callout, instead of being ignored altogether.

As an added bonus this means the following will also be valid too, which was something I had on my todo-list 😄 :

```markdown
> [!INFO]
> ```markdown
> > [!NOTE]
> > Codefenced callout within a callout
> ```
```

Result
```markdown
!!! info
    ```markdown
    > [!NOTE]
    > Codefenced callout within a callout
    ```
```

Please update when it gets released (in a couple minutes) and let me know if it's resolved

**Comment by gledos** [comment]
Thank you very much, the bug has been fixed.
